/*
zap-db

An easy to use JSON database created for memory management of slack bots

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetTokensByAdminToken struct for GetTokensByAdminToken
type GetTokensByAdminToken struct {
	Database *string `json:"database,omitempty"`
	Scopes *string `json:"scopes,omitempty"`
}

// NewGetTokensByAdminToken instantiates a new GetTokensByAdminToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTokensByAdminToken() *GetTokensByAdminToken {
	this := GetTokensByAdminToken{}
	return &this
}

// NewGetTokensByAdminTokenWithDefaults instantiates a new GetTokensByAdminToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTokensByAdminTokenWithDefaults() *GetTokensByAdminToken {
	this := GetTokensByAdminToken{}
	return &this
}

// GetDatabase returns the Database field value if set, zero value otherwise.
func (o *GetTokensByAdminToken) GetDatabase() string {
	if o == nil || o.Database == nil {
		var ret string
		return ret
	}
	return *o.Database
}

// GetDatabaseOk returns a tuple with the Database field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokensByAdminToken) GetDatabaseOk() (*string, bool) {
	if o == nil || o.Database == nil {
		return nil, false
	}
	return o.Database, true
}

// HasDatabase returns a boolean if a field has been set.
func (o *GetTokensByAdminToken) HasDatabase() bool {
	if o != nil && o.Database != nil {
		return true
	}

	return false
}

// SetDatabase gets a reference to the given string and assigns it to the Database field.
func (o *GetTokensByAdminToken) SetDatabase(v string) {
	o.Database = &v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *GetTokensByAdminToken) GetScopes() string {
	if o == nil || o.Scopes == nil {
		var ret string
		return ret
	}
	return *o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokensByAdminToken) GetScopesOk() (*string, bool) {
	if o == nil || o.Scopes == nil {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *GetTokensByAdminToken) HasScopes() bool {
	if o != nil && o.Scopes != nil {
		return true
	}

	return false
}

// SetScopes gets a reference to the given string and assigns it to the Scopes field.
func (o *GetTokensByAdminToken) SetScopes(v string) {
	o.Scopes = &v
}

func (o GetTokensByAdminToken) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Database != nil {
		toSerialize["database"] = o.Database
	}
	if o.Scopes != nil {
		toSerialize["scopes"] = o.Scopes
	}
	return json.Marshal(toSerialize)
}

type NullableGetTokensByAdminToken struct {
	value *GetTokensByAdminToken
	isSet bool
}

func (v NullableGetTokensByAdminToken) Get() *GetTokensByAdminToken {
	return v.value
}

func (v *NullableGetTokensByAdminToken) Set(val *GetTokensByAdminToken) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTokensByAdminToken) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTokensByAdminToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTokensByAdminToken(val *GetTokensByAdminToken) *NullableGetTokensByAdminToken {
	return &NullableGetTokensByAdminToken{value: val, isSet: true}
}

func (v NullableGetTokensByAdminToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTokensByAdminToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


