/*
zap-db

An easy to use JSON database created for memory management of slack bots

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateToken struct for CreateToken
type CreateToken struct {
	Message *string `json:"message,omitempty"`
	Token *string `json:"token,omitempty"`
}

// NewCreateToken instantiates a new CreateToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateToken() *CreateToken {
	this := CreateToken{}
	return &this
}

// NewCreateTokenWithDefaults instantiates a new CreateToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTokenWithDefaults() *CreateToken {
	this := CreateToken{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateToken) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateToken) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateToken) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateToken) SetMessage(v string) {
	o.Message = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *CreateToken) GetToken() string {
	if o == nil || o.Token == nil {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateToken) GetTokenOk() (*string, bool) {
	if o == nil || o.Token == nil {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *CreateToken) HasToken() bool {
	if o != nil && o.Token != nil {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *CreateToken) SetToken(v string) {
	o.Token = &v
}

func (o CreateToken) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.Token != nil {
		toSerialize["token"] = o.Token
	}
	return json.Marshal(toSerialize)
}

type NullableCreateToken struct {
	value *CreateToken
	isSet bool
}

func (v NullableCreateToken) Get() *CreateToken {
	return v.value
}

func (v *NullableCreateToken) Set(val *CreateToken) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateToken) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateToken(val *CreateToken) *NullableCreateToken {
	return &NullableCreateToken{value: val, isSet: true}
}

func (v NullableCreateToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


