name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2

      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Create a sample config file
        run: cp sample.config.json config.json

      - name: Build
        run: npm run build

  lint:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2

      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
